<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Package extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Package_model');
    } 

    /*
     * Listing of packages
     */
    function index()
    {
        $data['packages'] = $this->Package_model->get_all_packages();
        
        $data['_view'] = 'package/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new package
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $package_id = $this->Package_model->add_package($params);
            redirect('package/index');
        }
        else
        {            
            $data['_view'] = 'package/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a package
     */
    function edit($id)
    {   
        // check if the package exists before trying to edit it
        $data['package'] = $this->Package_model->get_package($id);
        
        if(isset($data['package']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Package_model->update_package($id,$params);            
                redirect('package/index');
            }
            else
            {
                $data['_view'] = 'package/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The package you are trying to edit does not exist.');
    } 

    /*
     * Deleting package
     */
    function remove($id)
    {
        $package = $this->Package_model->get_package($id);

        // check if the package exists before trying to delete it
        if(isset($package['id']))
        {
            $this->Package_model->delete_package($id);
            redirect('package/index');
        }
        else
            show_error('The package you are trying to delete does not exist.');
    }
    
}
