<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Channel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function by_package_id($id) {
        $this->db->order_by('channels.id', 'ASC');
        $this->db->join("channels_packages", 'channels_packages.channel_id = channels.id', 'inner');
        $this->db->where('channels_packages.package_id', $id);
        return $this->db->get('channels')->result_array();
    }

    public function channel_with_package($ch) {
        $this->db->where("hash", $ch);
    }
    
    /*
     * Get channel by id
     */
    function get_channel($id)
    {
        return $this->db->get_where('channels',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all channels
     */
    function get_all_channels()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('channels')->result_array();
    }
        
    /*
     * function to add new channel
     */
    function add_channel($params)
    {
        $this->db->insert('channels',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update channel
     */
    function update_channel($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('channels',$params);
    }
    
    /*
     * function to delete channel
     */
    function delete_channel($id)
    {
        return $this->db->delete('channels',array('id'=>$id));
    }
}
